"use client";
import { useActionState, useState } from "react";
import { recordPaymentAction, voidPaymentAction, type PaymentActionState } from "../actions/payment.actions";
import type { PayableChargeDto, PaymentMethodDto, PaymentSummaryDto } from "../types/payment.dto";
const initial:PaymentActionState={ok:false}; const input="min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2";
export function PaymentManagement({charges,methods,payments}:{charges:PayableChargeDto[];methods:PaymentMethodDto[];payments:PaymentSummaryDto[]}){const [selected,setSelected]=useState(charges[0]?.chargeId??"");const charge=charges.find(c=>c.chargeId===selected);const [state,action,pending]=useActionState(recordPaymentAction,initial);return <div className="mt-6 grid gap-6 xl:grid-cols-[0.8fr_1.2fr]"><section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p className="text-xs font-black uppercase tracking-[.16em] text-brand-green">Nuevo cobro</p><h2 className="mt-2 text-xl font-black text-ink">Registrar pago completo</h2>{charges.length===0?<p className="mt-4 text-gray">No hay cargos pendientes por cobrar.</p>:<form action={action} className="mt-5 grid gap-4"><label className="text-sm font-bold">Cargo<select className={input} name="chargeId" onChange={e=>setSelected(e.target.value)} value={selected}>{charges.map(c=><option key={c.chargeId} value={c.chargeId}>{c.memberLabel} · {c.currency} {c.amountDue} · vence {c.dueDate}</option>)}</select></label><input name="amount" type="hidden" value={charge?.amountDue??""}/><input name="currency" type="hidden" value={charge?.currency??""}/><div className="rounded-xl bg-slate-50 p-4"><p className="text-sm text-gray">Total a cobrar</p><strong className="text-2xl text-ink">{charge?.currency} {charge?.amountDue}</strong></div><label className="text-sm font-bold">Método<select className={input} name="paymentMethodId" required>{methods.map(m=><option key={m.id} value={m.id}>{m.name}</option>)}</select></label><label className="text-sm font-bold">Notas<input className={input} name="notes" maxLength={500}/></label><Message state={state}/><button className="min-h-11 rounded-lg bg-brand-green px-4 font-black text-white disabled:opacity-60" disabled={pending}>{pending?"Registrando…":"Registrar pago y generar recibo"}</button></form>}<p className="mt-4 text-xs text-gray">Se cobra el saldo completo en la moneda del cargo. La tasa vigente queda guardada como referencia histórica.</p></section><PaymentList payments={payments}/></div>}
function PaymentList({payments}:{payments:PaymentSummaryDto[]}){return <section className="rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="p-5"><h2 className="text-xl font-black text-ink">Pagos recientes</h2></div>{payments.length===0?<p className="p-5 text-gray">No hay pagos registrados.</p>:<div className="divide-y">{payments.map(p=><PaymentRow key={p.id} payment={p}/>)}</div>}</section>}
function PaymentRow({payment:p}:{payment:PaymentSummaryDto}){const [state,action,pending]=useActionState(voidPaymentAction,initial);return <article className="p-4"><div className="flex flex-wrap justify-between gap-3"><div><strong className="text-ink">{p.receiptNumber}</strong><p className="text-sm text-gray">{p.currency} {p.amount} · {p.status} · tasa C${p.appliedNioPerUsd}</p></div>{p.status==="settled"?<details><summary className="cursor-pointer text-sm font-black text-red-700">Anular</summary><form action={action} className="mt-2 flex gap-2"><input name="paymentId" type="hidden" value={p.id}/><input className={input} name="reason" placeholder="Motivo" required/><button className="rounded-lg bg-red-700 px-3 text-sm font-black text-white" disabled={pending}>Confirmar</button></form></details>:null}</div><Message state={state}/></article>}
function Message({state}:{state:PaymentActionState}){return state.message?<p className={`text-sm font-bold ${state.ok?"text-green-700":"text-red-700"}`}>{state.message}</p>:null;}
